In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

import numpy as np
import pandas as pd

# 10주차 내용

In [3]:
# Heart Failure Prediction Dataset 사용
# https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction?resource=download

heart_df = pd.read_csv('./heart.csv')
heart_df.head(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0


In [4]:
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [5]:
heart_df_no_missing = heart_df.dropna()
heart_df_no_missing

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [6]:
heart_df_cleaned = heart_df.dropna(how='all')
heart_df_cleaned

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [7]:
heart_df.dropna(axis=0, thresh = 4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [8]:
heart_df.dropna(thresh = 5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [9]:
heart_df.dropna(axis=1, how='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [10]:
heart_df['RestingBP'].mean()

132.39651416122004

In [11]:
heart_df['RestingBP'].median()

130.0

In [12]:
heart_df['RestingBP'].mode()

0    120
Name: RestingBP, dtype: int64

In [13]:
heart_df.fillna(0)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [14]:
heart_df['RestingBP'].fillna(heart_df['RestingBP'].mean())
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [15]:
heart_df['Cholesterol'].fillna(heart_df.groupby('Sex')['Cholesterol'].transform('mean'))
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [16]:
y_encoded, y_class = pd.factorize(heart_df['Sex'])

In [17]:
y_encoded

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
y_class

Index(['M', 'F'], dtype='object')

In [19]:
heart_df['Sex'] = y_encoded
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,1,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,0,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,1,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,0,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,0,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,0,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,1,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [20]:
pd.get_dummies(heart_df, dtype=int)

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,0,140,289,0,172,0.0,0,0,1,0,0,0,1,0,1,0,0,0,1
1,49,1,160,180,0,156,1.0,1,0,0,1,0,0,1,0,1,0,0,1,0
2,37,0,130,283,0,98,0.0,0,0,1,0,0,0,0,1,1,0,0,0,1
3,48,1,138,214,0,108,1.5,1,1,0,0,0,0,1,0,0,1,0,1,0
4,54,0,150,195,0,122,0.0,0,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,110,264,0,132,1.2,1,0,0,0,1,0,1,0,1,0,0,1,0
914,68,0,144,193,1,141,3.4,1,1,0,0,0,0,1,0,1,0,0,1,0
915,57,0,130,131,0,115,1.2,1,1,0,0,0,0,1,0,0,1,0,1,0
916,57,1,130,236,0,174,0.0,1,0,1,0,0,1,0,0,1,0,0,1,0


In [21]:
pd.get_dummies(heart_df['ST_Slope'], dtype=int)

,Down,Flat,Up
0,0,0,1
1,0,1,0
2,0,0,1
3,0,1,0
4,0,0,1
...,...,...,...
913,0,1,0
914,0,1,0
915,0,1,0
916,0,1,0


In [22]:
pd.get_dummies(heart_df[['ST_Slope']], dtype=int)

,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0,0,1
1,0,1,0
2,0,0,1
3,0,1,0
4,0,0,1
...,...,...,...
913,0,1,0
914,0,1,0
915,0,1,0
916,0,1,0


In [23]:
heart_df.values

array([[40, 0, 'ATA', ..., 0.0, 'Up', 0],
       [49, 1, 'NAP', ..., 1.0, 'Flat', 1],
       [37, 0, 'ATA', ..., 0.0, 'Up', 0],
       ...,
       [57, 0, 'ASY', ..., 1.2, 'Flat', 1],
       [57, 1, 'ATA', ..., 0.0, 'Flat', 1],
       [38, 0, 'NAP', ..., 0.0, 'Up', 0]], dtype=object)

In [24]:
X = [['man', 'from Seoul', 'uses Samsung'],
     ['woman', 'from Busan', 'uses Apple']]
X

[['man', 'from Seoul', 'uses Samsung'], ['woman', 'from Busan', 'uses Apple']]

In [25]:
from sklearn import preprocessing

enc = preprocessing.OrdinalEncoder()
enc.fit(X)

OrdinalEncoder()

In [26]:
enc.transform([['man', 'from Seoul', 'uses Samsung']])

array([[0., 1., 1.]])

In [27]:
enc.transform([['woman', 'from Busan', 'uses Apple']])

array([[1., 0., 0.]])

In [28]:
enc.transform([['man', 'from Busan', 'uses Apple']])

array([[0., 0., 0.]])

In [29]:
X = [['man'], ['woman'], ['woman']]
X

[['man'], ['woman'], ['woman']]

In [30]:
enc = preprocessing.OrdinalEncoder()
enc.fit_transform(X)

array([[0.],
       [1.],
       [1.]])

In [31]:
X = [['woman'], [np.nan], ['man'], ['man']]
X

[['woman'], [nan], ['man'], ['man']]

In [32]:
enc = preprocessing.OrdinalEncoder()
enc.fit_transform(X)

array([[ 1.],
       [nan],
       [ 0.],
       [ 0.]])

In [33]:
X = [['woman'], [np.nan], ['man'], ['man']]
X

[['woman'], [nan], ['man'], ['man']]

In [34]:
enc = preprocessing.OrdinalEncoder(encoded_missing_value=-1)
enc.fit_transform(X)

array([[ 1.],
       [-1.],
       [ 0.],
       [ 0.]])

In [35]:
X = [['man', 'from Seoul', 'uses Samsung'],
     ['woman', 'from Busan', 'uses Apple'],
     ['other', 'from Daejeon', 'uses other']]
X

[['man', 'from Seoul', 'uses Samsung'],
 ['woman', 'from Busan', 'uses Apple'],
 ['other', 'from Daejeon', 'uses other']]

In [36]:
enc = preprocessing.OneHotEncoder()
enc.fit(X)
enc.transform([['man', 'from Seoul', 'uses Samsung'],
               ['woman', 'from Busan', 'uses Samsung']]).toarray()

array([[1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1., 0.]])

In [37]:
enc.categories_

[array(['man', 'other', 'woman'], dtype=object),
 array(['from Busan', 'from Daejeon', 'from Seoul'], dtype=object),
 array(['uses Apple', 'uses Samsung', 'uses other'], dtype=object)]

In [38]:
gender = ['man', 'woman']
location = ['from Seoul', 'from Busan', 'from Daejeon']
phone = ['uses Samsung', 'uses Apple', 'uses other']

enc = preprocessing.OneHotEncoder(categories=[gender, location, phone])

X = [['man', 'from Busan', 'uses other'], ['woman', 'from Seoul', 'uses Samsung']]
enc.fit(X)

OneHotEncoder(categories=[['man', 'woman'],
                          ['from Seoul', 'from Busan', 'from Daejeon'],
                          ['uses Samsung', 'uses Apple', 'uses other']])

In [39]:
enc.transform([['woman', 'from Daejeon', 'uses Apple']]).toarray()

array([[0., 1., 0., 0., 1., 0., 1., 0.]])

In [40]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,1,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,0,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,1,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,0,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,0,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,0,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,1,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [41]:
(heart_df['RestingBP']-heart_df['RestingBP'].min())/(heart_df['RestingBP'].max() - heart_df['RestingBP'].min()) * (1-0) + 0

0      0.70
1      0.80
2      0.65
3      0.69
4      0.75
       ... 
913    0.55
914    0.72
915    0.65
916    0.65
917    0.69
Name: RestingBP, Length: 918, dtype: float64

In [42]:
(heart_df['Cholesterol']-heart_df['Cholesterol'].mean())/(heart_df['Cholesterol'].std())

0      0.824621
1     -0.171867
2      0.769768
3      0.138964
4     -0.034736
         ...   
913    0.596068
914   -0.053020
915   -0.619830
916    0.340090
917   -0.217578
Name: Cholesterol, Length: 918, dtype: float64

In [43]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler().fit(heart_df[['RestingBP', 'Cholesterol']])
heart_df_minmax = minmax_scale.transform(heart_df[['RestingBP', 'Cholesterol']])
heart_df_minmax

array([[0.7       , 0.47927032],
       [0.8       , 0.29850746],
       [0.65      , 0.46932007],
       ...,
       [0.65      , 0.2172471 ],
       [0.65      , 0.39137645],
       [0.69      , 0.29021559]])

In [44]:
std_scale = preprocessing.StandardScaler().fit(heart_df[['RestingBP', 'Cholesterol']])
heart_df_std = std_scale.transform(heart_df[['RestingBP', 'Cholesterol']])
heart_df_std

array([[ 0.41090889,  0.82507026],
       [ 1.49175234, -0.17196105],
       [-0.12951283,  0.7701878 ],
       ...,
       [-0.12951283, -0.62016778],
       [-0.12951283,  0.34027522],
       [ 0.30282455, -0.21769643]])

# 11주차 내용

In [46]:
# sklearn.datasets에서 load_wine 사용
from sklearn.datasets import load_wine

wine = load_wine()

In [47]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [48]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [49]:
wine.DESCR

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:      

In [50]:
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size = 0.2, random_state = 42)

In [51]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [52]:
print(f'test set accuracy: {model.score(X_test, y_test)}')

test set accuracy: 0.9444444444444444


In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [55]:
print(f'test set accuracy: {model.score(X_test, y_test)}')

test set accuracy: 1.0


In [56]:
import sklearn.svm as svm

In [57]:
model = svm.SVC(kernel = 'linear', random_state=42)
model.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [58]:
print(f'test set accuracy: {model.score(X_test, y_test)}')

test set accuracy: 0.9444444444444444


In [59]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [61]:
print(f'test set accuracy: {model.score(X_test, y_test)}')

test set accuracy: 0.75


In [62]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [63]:
pred = model.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score

print('정확도(Accuracy): {:.4f}'.format(accuracy_score(y_test, pred)))

정확도(Accuracy): 1.0000


In [65]:
from sklearn.metrics import precision_score, recall_score

print('정밀도(Precision): {:.4f}'.format(precision_score(y_test,pred, average='macro')))
print('재현율(Recall): {:.4f}'.format(recall_score(y_test,pred, average='macro')))

정밀도(Precision): 1.0000
재현율(Recall): 1.0000


In [66]:
from sklearn.metrics import f1_score

print('F1_score: {:.4f}'.format(f1_score(y_test,pred, average='macro')))

F1_score: 1.0000
