# 과제 1

In [9]:
import numpy as np

A = np.array([[1, 0, 2], [0, 1, 1], [1, 2, 2]])
E = np.identity(3)
# A*B = 2B - A
# A*B - 2B = -A
# (A - 2*E)*B = -A
C = A - 2*E
D = -A

B = np.dot(np.linalg.inv(C), D)
print(B)

[[ 0.  -2.  -1. ]
 [-0.5  0.  -0.5]
 [-0.5 -1.  -1.5]]


# 과제 2-1

In [1]:
import numpy as np

A = np.array([[2, -1, -3],
               [-1, -2, -3],
               [1, 1, 4]])
B = np. array([[2],
                [-1],
                [1]])

X = np.linalg.solve(A, B)
print(X)

[[ 1.]
 [-0.]
 [ 0.]]


# 과제 2-2

In [7]:
import numpy as np

A = np.array([[2, -1, -3],
              [-4, 2, 6],
              [3, 1, 4]])
B = np.array([[2],
              [-1],
              [1]])

try:
    X = np.linalg.solve(A, B)
    print(X)
except np.linalg.LinAlgError as e:
    print("Error :",e)

Error : Singular matrix


# 과제 3

In [23]:
import numpy as np

def f(array):
    n = len(array)
    A = []

    for i in range(n):
        for j in range(n):
            A.append(array[i][j])

    result = np.array(A)
    return result

f(np.array([[1,2],[2,3]]))

array([1, 2, 2, 3])

In [29]:
import numpy as np

def f(array):
    n = len(array)
    A = []

    for i in range(n):
        for j in range(n):
            A.append(array[i][j])

    result = np.array(A)
    return result

f(np.array([[1,2,3],[2,3,4],[3,4,5]]))

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

# 과제 4

In [37]:
import numpy as np

A = np.array([[0.6, 0.3],
              [0.4, 0.7]])
init_vector = np.array([[0, 1]])
x0 = init_vector.T
x1 = A.dot(x0)
x2 = A.dot(x1)
print(x2)

[[0.39]
 [0.61]]


# 과제 5

In [45]:
import numpy as np

def x(t):
    A = np.array([[0.6, 0.3],
                  [0.4, 0.7]])
    init_vector = np.array([[1],
                            [0]])
    xt = init_vector
    
    if t == 0:
        return xt
    else:
        for i in range(t):
            xt = A.dot(xt)
        return xt

x(10)

array([[0.4285748],
       [0.5714252]])

# 과제 6